name: "build"

on: ["pull_request", "push"]

jobs:
  build:
    strategy:
      matrix:
        java: ["1.8", "11", "14"]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2"
      - name: "setup jdk ${{ matrix.java }}"
        uses: "actions/setup-java@v1"
        with:
          java-version: "${{ matrix.java }}"
      - name: "build"
        run: "./gradlew build"
