name: "rebuild docs on release"

on:
  release:
    types: ["created", "edited", "deleted"]
  workflow_dispatch:

jobs:
  call-build:
    uses: "KyoriPowered/.github/.github/workflows/shared-rebuild-docs.yaml@trunk"
